Repository DDD-5/undertheriver-sgsg-backend, pull requests merged in 2021-04, with the labels that each got.

#27 feat: BaseEntity 추가
  src/main/java/com/undertheriver/sgsg/common/domain/BaseEntity.java
  src/main/java/com/undertheriver/sgsg/config/JpaConfig.java
Labels: Feature

#28 feat: User 도메인 추가
  src/main/java/com/undertheriver/sgsg/config/BCryptPasswordEncoderConfig.java
  src/main/java/com/undertheriver/sgsg/user/domain/PasswordConverter.java
  src/main/java/com/undertheriver/sgsg/user/domain/User.java
  src/main/java/com/undertheriver/sgsg/user/domain/UserRepository.java
  src/main/java/com/undertheriver/sgsg/user/domain/UserSecretMemoPassword.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/undertheriver/sgsg/user/domain/UserRepositoryTest.java
  src/test/resources/application.yml
Labels: Feature

#35 feat: Folder API 추가
  src/main/java/com/undertheriver/sgsg/common/domain/BaseEntity.java
  src/main/java/com/undertheriver/sgsg/foler/controller/FolderController.java
  src/main/java/com/undertheriver/sgsg/foler/domain/Folder.java
  src/main/java/com/undertheriver/sgsg/foler/domain/FolderColor.java
  src/main/java/com/undertheriver/sgsg/foler/domain/dto/FolderDto.java
  src/main/java/com/undertheriver/sgsg/foler/repository/FolderRepository.java
  src/main/java/com/undertheriver/sgsg/memo/controller/MemoController.java
  src/main/java/com/undertheriver/sgsg/memo/domain/Memo.java
  src/main/java/com/undertheriver/sgsg/memo/domain/dto/request/CreateMemoRequestDto.java
  src/main/java/com/undertheriver/sgsg/memo/domain/dto/response/ReadMemoResponseDto.java
  src/main/java/com/undertheriver/sgsg/user/domain/User.java
  src/main/resources/application.yml
  src/test/java/com/undertheriver/sgsg/foler/repository/FolderRepositoryTest.java
Labels: Feature

#43 fix: application.yml dialect 옵션 삭제
  src/main/resources/application.yml
Labels: Bug

#45 feat: Authtication 예외 핸들러 추가
  src/main/java/com/undertheriver/sgsg/config/SpringSecurityConfig.java
  src/main/java/com/undertheriver/sgsg/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/undertheriver/sgsg/config/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/undertheriver/sgsg/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/undertheriver/sgsg/util/HttpResponseUtils.java
Labels: Server

#48 chore: 깃헙액션에 서브모듈 적용
  .github/workflows/deploy.yml
  src/test/java/com/undertheriver/sgsg/foler/repository/FolderRepositoryTest.java
  src/test/resources/application.yml
Labels: Infra

#59 feat: 유저정보, 삭제 API 구현
  build.gradle
  src/main/java/com/undertheriver/sgsg/common/exception/ModelNotFoundException.java
  src/main/java/com/undertheriver/sgsg/config/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/undertheriver/sgsg/user/controller/UserController.java
  src/main/java/com/undertheriver/sgsg/user/controller/dto/UserDto.java
  src/main/java/com/undertheriver/sgsg/user/domain/User.java
  src/main/java/com/undertheriver/sgsg/user/service/UserService.java
  src/test/java/com/undertheriver/sgsg/acceptance/AcceptanceTest.java
  src/test/java/com/undertheriver/sgsg/user/controller/UserControllerTest.java
  src/test/resources/query/user-delete.sql
  src/test/resources/query/user.sql
Labels: Server
