Repository DDD-5/undertheriver-sgsg-backend, pull requests merged in 2021-07, with the labels that each got.

#153 feat: 폴더 이름 중복 검사
  src/main/java/com/undertheriver/sgsg/common/exception/FolderValidationException.java
  src/main/java/com/undertheriver/sgsg/foler/repository/FolderRepository.java
  src/main/java/com/undertheriver/sgsg/foler/service/FolderService.java
  src/main/java/com/undertheriver/sgsg/memo/service/MemoService.java
  src/test/java/com/undertheriver/sgsg/foler/repository/FolderRepositoryTest.java
  src/test/java/com/undertheriver/sgsg/foler/service/FolderServiceTest.java
  src/test/java/com/undertheriver/sgsg/memo/service/MemoServiceTest.java
Labels: Feature

#159 fix: 인증실패시 401에러를 발생하도록 변경
  src/main/java/com/undertheriver/sgsg/config/SecurityConfig.java
Labels: Feature, Server

#181 chore: CI, CD 파이프라인 분리
  .github/workflows/CI&CD.yml
  .github/workflows/CI.yml
Labels: Infra

#183 feat: 유저와 폴더의 객체 관계를 제거 한다.
  src/main/java/com/undertheriver/sgsg/foler/domain/Folder.java
  src/main/java/com/undertheriver/sgsg/foler/domain/FolderColor.java
  src/main/java/com/undertheriver/sgsg/foler/domain/dto/FolderDto.java
  src/main/java/com/undertheriver/sgsg/foler/repository/FolderRepository.java
  src/main/java/com/undertheriver/sgsg/foler/service/FolderService.java
  src/main/java/com/undertheriver/sgsg/memo/domain/Memo.java
  src/main/java/com/undertheriver/sgsg/memo/repository/MemoRepository.java
  src/main/java/com/undertheriver/sgsg/memo/service/MemoService.java
  src/main/java/com/undertheriver/sgsg/user/domain/User.java
  src/test/java/com/undertheriver/sgsg/foler/repository/FolderRepositoryTest.java
  src/test/java/com/undertheriver/sgsg/foler/service/FolderServiceTest.java
  src/test/java/com/undertheriver/sgsg/memo/repository/MemoRepositoryTest.java
  src/test/java/com/undertheriver/sgsg/memo/service/MemoServiceTest.java
  src/test/java/com/undertheriver/sgsg/user/domain/FolderColorTest.java
Labels: Feature

#173 docs: README 업데이트
  README.md
Labels: Docs
